name: Node CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install backend dependencies
        run: npm install
        working-directory: backend
      - name: Install frontend dependencies
        run: npm install
        working-directory: frontend
      - name: Testing backend
        run: npm test
        working-directory: backend
      - name: Testing frontend
        run: npm test
        working-directory: frontend
        env:
          CI: true
